name: CI

on:
  pull_request:
    paths:
      - 'recipes/**'
      - 'trassir/**'
      - '*.py'
      - '.github/workflows/all.yml'
  push:
    branches:
      - master
    paths:
      - 'recipes/**'
      - 'trassir/**'
      - '*.py'
      - '.github/workflows/all.yml'

env:
  CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}
  REMOTES_MASTER: ${{ secrets.REMOTES_MASTER }}
  REMOTES_STAGING: ${{ secrets.REMOTES_STAGING }}
  REMOTES_UPLOAD_USER: ${{ secrets.REMOTES_UPLOAD_USER }}
  IS_PURE_C: true

jobs:
  conan:
    strategy:
      matrix:
        build: ['windows-2019-release',
                'windows-2019-debug',
                'linux-gcc8-release',
                'linux-gcc8-debug',
                'macos-release'
                ]
        include:
          - build: 'windows-2019-release'
            os: 'windows-2019'
            conan_txt: 'trassir/win32-vc16/conanfile.txt'
            conan_profile: 'trassir/win32-vc16/conanprofile.release'
            build_types: 'Release'
          - build: 'windows-2019-debug'
            os: 'windows-2019'
            conan_txt: 'trassir/win32-vc16/conanfile.txt'
            conan_profile: 'trassir/win32-vc16/conanprofile.debug'
            build_types: 'Debug'
          - build: 'linux-gcc8-release'
            os: 'ubuntu-latest'
            conan_txt: 'trassir/lnvr-gcc8/conanfile.txt'
            conan_profile: 'trassir/lnvr-gcc8/conanprofile'
            build_types: 'Release'
            container: 'trassiross/conan-gcc8'
          - build: 'linux-gcc8-debug'
            os: 'ubuntu-latest'
            conan_txt: 'trassir/lnvr-gcc8/conanfile.txt'
            conan_profile: 'trassir/lnvr-gcc8/conanprofile'
            build_types: 'Debug'
            container: 'trassiross/conan-gcc8'
          - build: 'macos-release'
            os: 'macos-10.15'
            conan_txt: 'trassir/mac-clang11/conanfile.txt'
            conan_profile: 'trassir/mac-clang11/conanprofile.release'
            build_types: 'Release'
            deployment-target: '10.14'
            xcode_version: '11.4'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Configure git
        run: git config --global core.autocrlf false
        shell: bash
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: sources
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Build and Upload
        run: |
          pip install conan
          python sources/build.py
        env:
          CONAN_TXT: ${{ matrix.conan_txt }}
          CONAN_PROFILE: ${{ matrix.conan_profile }}
          CONAN_BUILD_TYPES: ${{ matrix.build_types }}
          CONAN_ARCHS: ${{ matrix.archs }}
          MACOSX_DEPLOYMENT_TARGET: ${{ matrix.deployment-target }}
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app/Contents/Developer
