name: ffmpeg-3.3.1 CI

on:
  pull_request:
    paths:
      - 'recipes/ffmpeg/3.3.1/**'
      - 'build.py'
      - '.github/workflows/ffmpeg-3.3.1.yml'
  push:
    branches:
      - master
    paths:
      - 'recipes/ffmpeg/3.3.1/**'
      - 'build.py'
      - '.github/workflows/ffmpeg-3.3.1.yml'

env:
  CONAN_PASSWORD: ${{ secrets.BintrayApiKey }}
  CONAN_REFERENCE: 'ffmpeg/3.3.1'
  IS_PURE_C: true

jobs:
  ffmpeg:
    strategy:
      matrix:
        build: ['linux-gcc8', 'macos']
        include:
          - build: 'linux-gcc8'
            os: 'ubuntu-latest'
            compiler: 'gcc'
            compiler_version: '8'
            docker_image: 'conanio/gcc8'
            build_types: 'Release'
            archs: 'x86_64'
          - build: 'macos'
            os: 'macos-10.15'
            build_types: 'Release'
            archs: 'x86_64'
            compiler: 'apple_clang'
            compiler_version: '11.0'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install pkg-config
        if: matrix.os == 'macos-10.15'
        run: brew install pkg-config
      - name: Configure git
        run: git config --global core.autocrlf input
        shell: bash
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: sources
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Build and Optionally Upload
        uses: trassir/run-cpt@v0.2.2-trassir
        with:
          install: custom
          # TODO: replace when https://github.com/conan-io/conan-package-tools/issues/479 will be fixed upstream
          custom-package: git+https://github.com/trassir/conan-package-tools@fix-479-trassir
          work-dir: sources/recipes/ffmpeg/3.3.1
          build-script: ../../../build.py
          compiler: ${{ matrix.compiler }}
          compiler-versions: ${{ matrix.compiler_version }}
          docker-images: ${{ matrix.docker_image }}
        env:
          CONAN_OPTIONS: "ffmpeg:shared=True"
          CONAN_SHARED_OPTION_NAME: False
          CONAN_VISUAL_RUNTIMES: ${{ matrix.vs_runtimes }}
          CONAN_ARCHS: ${{ matrix.archs }}
          CONAN_BUILD_TYPES: ${{ matrix.build_types }}
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app/Contents/Developer
