name: ffmpeg-4.2.1 CI

on:
  pull_request:
    paths:
      - 'recipes/ffmpeg/4.2.1/**'
      - 'build.py'
      - '.github/workflows/ffmpeg-4.2.1.yml'
  push:
    branches:
      - master
    paths:
      - 'recipes/ffmpeg/4.2.1/**'
      - 'build.py'
      - '.github/workflows/ffmpeg-4.2.1.yml'

env:
  CONAN_PASSWORD: ${{ secrets.BintrayApiKey }}
  CONAN_REFERENCE: 'ffmpeg/4.2.1'
  IS_PURE_C: true

jobs:
  ffmpeg:
    strategy:
      matrix:
        build: ['linux-gcc8']
        include:
          - build: 'linux-gcc8'
            os: 'ubuntu-latest'
            compiler: 'gcc'
            compiler_version: '8'
            docker_image: 'trassiross/conan-gcc8'
            build_types: 'Release'
            archs: 'x86_64'
            conan-options: 'ffmpeg:openjpeg=False,
                            ffmpeg:pulse=False,
                            ffmpeg:fdk_aac=False,
                            ffmpeg:mp3lame=False,
                            ffmpeg:vpx=False,
                            ffmpeg:vorbis=False,
                            ffmpeg:opus=False,
                            ffpeg:zmq=False,
                            ffmpeg:sdl2=False,
                            ffmpeg:x264=False,
                            ffmpeg:x265=False,
                            ffmpeg:vpx=False,
                            ffmpeg:xcb=False,
                            ffmpeg:openssl=False,
                            ffmpeg:vaapi=False,
                            ffmpeg:vdpau=False
                            '
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install pkg-config
        if: matrix.os == 'macos-10.15'
        run: brew install pkg-config
      - name: Configure git
        run: git config --global core.autocrlf input
        shell: bash
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: sources
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Build and Optionally Upload
        uses: trassir/run-cpt@v0.2.2-trassir
        with:
          install: custom
          # TODO: replace when https://github.com/conan-io/conan-package-tools/issues/479 will be fixed upstream
          custom-package: git+https://github.com/trassir/conan-package-tools@fix-479-trassir
          work-dir: sources/recipes/ffmpeg/4.2.1
          build-script: ../../../build.py
          compiler: ${{ matrix.compiler }}
          compiler-versions: ${{ matrix.compiler_version }}
          docker-images: ${{ matrix.docker_image }}
        env:
          CONAN_OPTIONS: ${{ matrix.conan-options }}
          MACOSX_DEPLOYMENT_TARGET: ${{ matrix.deployment-target }}
          CONAN_VISUAL_RUNTIMES: ${{ matrix.vs_runtimes }}
          CONAN_ARCHS: ${{ matrix.archs }}
          CONAN_BUILD_TYPES: ${{ matrix.build_types }}
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app/Contents/Developer
