name: jsoncpp CI

on:
  pull_request:
    paths:
      - 'recipes/jsoncpp/all/**'
      - 'build.py'
      - '.github/workflows/jsoncpp.yml'
  push:
    branches:
      - master
    paths:
      - 'recipes/jsoncpp/all/**'
      - 'build.py'
      - '.github/workflows/jsoncpp.yml'

env:
  CONAN_PASSWORD: ${{ secrets.BintrayApiKey }}

jobs:
  jsoncpp:
    strategy:
      matrix:
        build: ['linux-gcc8', 'windows-2019-release', 'macos']
        include:
          - build: 'linux-gcc8'
            os: 'ubuntu-latest'
            compiler: 'gcc'
            compiler_version: '8'
            docker_image: 'trassiross/conan-gcc8:frombase'
            build_types: 'Release'
            archs: 'x86_64'
            conan_reference: "jsoncpp/1.8.3"
          - build: 'windows-2019-release'
            os: 'windows-2019'
            build_types: 'Release'
            compiler: 'vs'
            compiler_version: '16'
            vs_runtimes: 'MD,MT'
            archs: 'x86_64'
            conan_reference: "jsoncpp/1.8.3"
          - build: 'macos'
            os: 'macos-10.15'
            build_types: 'Release'
            archs: 'x86_64'
            compiler: 'apple_clang'
            compiler_version: '11.0'
            xcode_version: '11.3.1'
            conan_reference: "jsoncpp/1.8.3"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Configure git
        run: git config --global core.autocrlf false
        shell: bash
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: sources
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Build and Optionally Upload
        uses: trassir/run-cpt@v0.2.2-trassir
        with:
          install: custom
          # TODO: replace when https://github.com/conan-io/conan-package-tools/issues/479 will be fixed upstream
          custom-package: git+https://github.com/trassir/conan-package-tools@fix-479-trassir
          work-dir: sources/recipes/jsoncpp/all
          build-script: ../../../build.py
          compiler: ${{ matrix.compiler }}
          compiler-versions: ${{ matrix.compiler_version }}
          docker-images: ${{ matrix.docker_image }}
        env:
          CONAN_OPTIONS: "jsoncpp:shared=True"
          CONAN_SHARED_OPTION_NAME: False
          CONAN_REFERENCE: ${{ matrix.conan_reference }}
          CONAN_VISUAL_RUNTIMES: ${{ matrix.vs_runtimes }}
          CONAN_ARCHS: ${{ matrix.archs }}
          CONAN_BUILD_TYPES: ${{ matrix.build_types }}
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app/Contents/Developer
