name: openal CI

on:
  pull_request:
    paths:
      - 'recipes/openal/all/**'
      - 'build.py'
      - '.github/workflows/openal.yml'
  push:
    branches:
      - master
    paths:
      - 'recipes/openal/all/**'
      - 'build.py'
      - '.github/workflows/openal.yml'

env:
  CONAN_PASSWORD: ${{ secrets.BintrayApiKey }}
  IS_PURE_C: true

jobs:
  openal:
    strategy:
      matrix:
        build: ['macos']
        openal_versions: ['1.20.1']
        include:
          - build: 'macos'
            os: 'macos-latest'
            build_types: 'Release,Debug'
            archs: 'x86_64'
            compiler: 'apple_clang'
            compiler_version: '11.0'
            xcode_version: '11.3.1'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Configure git
        run: git config --global core.autocrlf false
        shell: bash
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: sources
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Build and Optionally Upload
        uses: trassir/run-cpt@v0.2.2-trassir
        with:
          install: custom
          # TODO: replace when https://github.com/conan-io/conan-package-tools/issues/479 will be fixed upstream
          custom-package: git+https://github.com/trassir/conan-package-tools@fix-479-trassir
          work-dir: sources/recipes/openal/all
          build-script: ../../../build.py
          compiler: ${{ matrix.compiler }}
          compiler-versions: ${{ matrix.compiler_version }}
          docker-images: ${{ matrix.docker_image }}
        env:
          CONAN_REFERENCE: 'openal/${{ matrix.openal_versions }}'
          CONAN_OPTIONS: "openal:shared=True"
          CONAN_SHARED_OPTION_NAME: "openal:shared"
          CONAN_VISUAL_RUNTIMES: ${{ matrix.vs_runtimes }}
          CONAN_ARCHS: ${{ matrix.archs }}
          CONAN_BUILD_TYPES: ${{ matrix.build_types }}
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app/Contents/Developer
