name: Lint
on:
  pull_request:
    paths:
      - 'builder/**'
      - '.github/workflows/prospector.yml'
  push:
    branches:
      - master
    paths:
      - 'builder/**'
      - '.github/workflows/prospector.yml'

jobs:
  lint:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    python_version: 3.9
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python_version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python_version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade conan
        pip install prospector
    - name: Lint with prospector
      run: |
        prospector -F --strictness veryhigh builder
