name: stawberryperl CI

on:
  pull_request:
    paths:
      - 'recipes/strawberryperl/ALL/**'
      - 'build.py'
      - '.github/workflows/strawberryperl-5.30.0.1.yml'
  push:
    branches:
      - master
    paths:
      - 'recipes/strawberryperl/ALL/**'
      - 'build.py'
      - '.github/workflows/strawberryperl-5.30.0.1.yml'


jobs:
  strawberryperl_5_30_0_1:
    runs-on: 'windows-2019'
    steps:
      - name: Configure git
        run: git config --global core.autocrlf false
        shell: bash
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: sources
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Build and Optionally Upload
        uses: trassir/run-cpt@v0.2.2-trassir
        with:
          install: custom
          # TODO: replace when https://github.com/conan-io/conan-package-tools/issues/479 will be fixed upstream
          custom-package: git+https://github.com/trassir/conan-package-tools@fix-479-trassir
          work-dir: sources/recipes/strawberryperl/ALL
          build-script: ../../../build.py
          compiler: 'vs'
          compiler-versions: '16'
        env:
          CONAN_PASSWORD: ${{ secrets.BintrayApiKey }}
          CONAN_ARCHS: 'x86_64'
          CONAN_REFERENCE: 'strawberryperl/5.30.0.1'
