name: zlib-1.2.11 CI

on:
  pull_request:
    paths:
      - 'recipes/zlib/1.2.11/**'
      - 'build.py'
      - '.github/workflows/zlib-1.2.11.yml'
  push:
    branches:
      - master
    paths:
      - 'recipes/zlib/1.2.11/**'
      - 'build.py'
      - '.github/workflows/zlib-1.2.11.yml'

env:
  CONAN_PASSWORD: ${{ secrets.BintrayApiKey }}
  IS_PURE_C: true

jobs:
  zlib_1_2_11:
    strategy:
      matrix:
        build: ['macos']
        include:
          - build: 'macos'
            os: 'macos-10.15'
            deployment-target: '10.14'
            build_types: 'Release'
            archs: 'x86_64'
            compiler: 'apple_clang'
            compiler_version: '11.0'
            xcode_version: '11.4'
            conan_reference: 'zlib/1.2.11'
            conan_txt: 'conanfile-osx.txt'
            conan_pr: 'conanprofile.osx'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Configure git
        run: git config --global core.autocrlf false
        shell: bash
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: sources
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Build and Optionally Upload
        uses: trassir/run-cpt@v0.2.2-trassir
        with:
          install: custom
          # TODO: replace when https://github.com/conan-io/conan-package-tools/issues/479 will be fixed upstream
          custom-package: git+https://github.com/trassir/conan-package-tools@log-remotes-before-upload
          work-dir: sources/recipes/zlib/1.2.11
          build-script: ../../../build.py
          compiler: ${{ matrix.compiler }}
          compiler-versions: ${{ matrix.compiler_version }}
          docker-images: ${{ matrix.docker_image }}
        env:
          CONAN_TXT: ${{ matrix.conan_txt }}
          CONAN_PR: ${{ matrix.conan_pr }}
          MACOSX_DEPLOYMENT_TARGET: ${{ matrix.deployment-target }}
          CONAN_REFERENCE: ${{ matrix.conan_reference }}
          CONAN_VISUAL_RUNTIMES: ${{ matrix.vs_runtimes }}
          CONAN_ARCHS: ${{ matrix.archs }}
          CONAN_BUILD_TYPES: ${{ matrix.build_types }}
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app/Contents/Developer
