name: xcb-proto-1.13 CI

on:
  pull_request:
    paths:
      - 'recipes/x11/all/xcb-proto/1.13/**'
      - 'build.py'
      - '.github/workflows/x11/xcb-proto-1.13.yml'
  push:
    branches:
      - master
    paths:
      - 'recipes/x11/all/xcb-proto/1.13/**'
      - 'build.py'
      - '.github/workflows/x11/xcb-proto-1.13.yml'

env:
  CONAN_PASSWORD: ${{ secrets.BintrayApiKey }}
  IS_PURE_C: true

jobs:
  xcb-proto:
    strategy:
      matrix:
        build: ['linux-gcc4.8', 'linux-gcc8', 'linux-gcc9']
        xcb-proto_versions: ['1.13']
        include:
          - build: 'linux-gcc4.8'
            os: 'ubuntu-latest'
            compiler: 'gcc'
            compiler_version: '4.8'
            docker_image: 'conanio/gcc48'
            build_types: 'Release,Debug'
            archs: 'x86,x86_64'
          - build: 'linux-gcc8'
            os: 'ubuntu-latest'
            compiler: 'gcc'
            compiler_version: '8'
            docker_image: 'conanio/gcc8'
            build_types: 'Release,Debug'
            archs: 'x86,x86_64'
          - build: 'linux-gcc9'
            os: 'ubuntu-latest'
            compiler: 'gcc'
            compiler_version: '9'
            docker_image: 'conanio/gcc9'
            build_types: 'Release,Debug'
            archs: 'x86,x86_64'          
    runs-on: ${{ matrix.os }}
    steps:
      - name: Configure git
        run: git config --global core.autocrlf false
        shell: bash
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: sources
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: Build and Optionally Upload
        uses: trassir/run-cpt@v0.2.2-trassir
        with:
          install: custom
          # TODO: replace when https://github.com/conan-io/conan-package-tools/issues/479 will be fixed upstream
          custom-package: git+https://github.com/trassir/conan-package-tools@fix-479-trassir
          work-dir: sources/recipes/x11/all/xcb-proto/${{ matrix.xcb-proto_versions }}
          build-script: ../../../build.py
          compiler: ${{ matrix.compiler }}
          compiler-versions: ${{ matrix.compiler_version }}
          docker-images: ${{ matrix.docker_image }}
        env:
          CONAN_REFERENCE: 'xcb-proto/${{ matrix.xcb-proto_versions }}'
          CONAN_VISUAL_RUNTIMES: ${{ matrix.vs_runtimes }}
          CONAN_ARCHS: ${{ matrix.archs }}
          CONAN_BUILD_TYPES: ${{ matrix.build_types }}
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app/Contents/Developer
